
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andre
 */
public class CalculadoraLucro extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraLucro
     */
    public CalculadoraLucro() {
        initComponents();
        dispose();
        this.setUndecorated(true);
        this.setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        encerrarButton = new javax.swing.JLabel();
        limparButton = new javax.swing.JLabel();
        valorLucro = new javax.swing.JLabel();
        precoVenda = new javax.swing.JLabel();
        campo2 = new javax.swing.JTextField();
        campo1 = new javax.swing.JTextField();
        calcularButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        encerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/encerrarButton.png"))); // NOI18N
        encerrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encerrarButtonMouseClicked(evt);
            }
        });
        getContentPane().add(encerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 40, -1));

        limparButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limparButton.png"))); // NOI18N
        limparButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparButtonMouseClicked(evt);
            }
        });
        getContentPane().add(limparButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        valorLucro.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        valorLucro.setText("                ");
        getContentPane().add(valorLucro, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 302, 90, 20));

        precoVenda.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        precoVenda.setText("       ");
        getContentPane().add(precoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 90, 20));

        campo2.setBackground(new java.awt.Color(213, 229, 255));
        campo2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        campo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo2ActionPerformed(evt);
            }
        });
        getContentPane().add(campo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 70, 20));

        campo1.setBackground(new java.awt.Color(213, 229, 255));
        campo1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo1ActionPerformed(evt);
            }
        });
        getContentPane().add(campo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, 20));

        calcularButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calcularButton.png"))); // NOI18N
        calcularButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularButtonMouseClicked(evt);
            }
        });
        getContentPane().add(calcularButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadoraLucroForm.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void encerrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encerrarButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_encerrarButtonMouseClicked

    private void calcularButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularButtonMouseClicked
        // TODO add your handling code here:
        //colocar aqui programação para calculo
        
        double n1 = Double.parseDouble(campo1.getText());
        double n2 = Double.parseDouble(campo2.getText());
        double resultado = n1+((n1/100)*n2);
        double resultadoLucro = resultado-n1;
        precoVenda.setText(String.valueOf(resultado));
        valorLucro.setText(String.valueOf(resultadoLucro));
    }//GEN-LAST:event_calcularButtonMouseClicked
    
    private void campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campo1ActionPerformed

    private void campo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo2ActionPerformed

    private void limparButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonMouseClicked
        // TODO add your handling code here:
        campo1.setText("");
        campo2.setText("");
        precoVenda.setText("");
        valorLucro.setText("");
        campo1.requestFocus();
    }//GEN-LAST:event_limparButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLucro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLucro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLucro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLucro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraLucro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcularButton;
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JLabel encerrarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel limparButton;
    private javax.swing.JLabel precoVenda;
    private javax.swing.JLabel valorLucro;
    // End of variables declaration//GEN-END:variables
}
